### ISSUE TITLE
something is wrong with the version.

### ISSUE THREAD

**Issue by SethJHursey** [HXCHS/HackersX-Unblocked-Websites#10]
I don't know what to do from here.
![image](https://github.com/HXCHS/HackersX-Unblocked-Websites/assets/153306268/67948721-1542-4495-af9f-378fea0f1d24)

**Comment by HXCHS** [comment]
You on a chromebook right

**Comment by HudsonDukette** [comment]
the same thing hapened to me
and im on a mac

**Comment by HXCHS** [comment]
Try this link: 
https://incog.dev/#

Also Follow me on TT I will start posting links that I will verify works with securly when I get 10 followers, its a new account.

https://www.tiktok.com/@theofficial_hackersx

**Comment by HudsonDukette** [comment]
its blocked lol

**Comment by HXCHS** [comment]
Did you check the others?

**Comment by R6IIIXIII** [comment]
> Did you check the others?
the other links are proxys to bring you to a website were you can look up your own things. we want to be able to have securly turned on and off with the chromebook but this blocker is out dated. please do somthing i want to be able to block securly like i used to be able to

**Comment by HXCHS** [comment]
> > Did you check the others?
> > the other links are proxys to bring you to a website were you can look up your own things. we want to be able to have securly turned on and off with the chromebook but this blocker is out dated. please do somthing i want to be able to block securly like i used to be able to

Ill work on it

**Comment by R6IIIXIII** [comment]
> Ill work on it

thankyou
