### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by OrangeThunderFire** [HXCHS/HackersX-Unblocked-Websites#16]
It used to work very good, but now it doesn't work anymore. I turn securly off during the code, but when I go to a blocked website it still showed block. It worked fine until the new update.

**Comment by HXCHS** [comment]
The new chromebook update?

**Comment by OrangeThunderFire** [comment]
Yes the new chromebook update.

**Comment by OrangeThunderFire** [comment]
what can we do about it, I can't play my favorite game anymore, finalearth.com

**Comment by OrangeThunderFire** [comment]
HXCHS, are you not going to do anything?
