### ISSUE TITLE
Its been blocked.

### ISSUE THREAD

**Issue by mountedtheexo** [HXCHS/HackersX-Unblocked-Websites#20]
Looks like securely found out and blocked it. is there anything we can do?

**Comment by mountedtheexo** [comment]
im talking about ubhub!

**Comment by St47b0und** [comment]
well, if the author would give the hmtl, js, ect for the website then you could just host your own.

**Comment by OrangeThunderFire** [comment]
how do you host a proxy server on chromeboo>

**Comment by mountedtheexo** [comment]
im not even sure myself

**Comment by OrangeThunderFire** [comment]
prob videos on it

**Comment by St47b0und** [comment]
codepen, renderer, ect
