### ISSUE TITLE
Why the securly disable hack isn't working

### ISSUE THREAD

**Issue by EEEEHI** [HXCHS/HackersX-Unblocked-Websites#21]
There's currently a new update for securly and so that is why this hack is not working for some. The hack only works if you have the not updated version of securly.

Hack has been blocked.

Things I noticed:
When you drag it up, it shows the securly sign and so securly might have already got the website. 
[Screen recording 2024-01-24 1.11.29 PM.webm](https://github.com/HXCHS/HackersX-Unblocked-Websites/assets/131414490/d3109b27-036e-45f0-9945-97a295cc3692)

Everything works up until the drag. 
Hopefully this hack can work again. 
I also heard that this hack can be used on a different website- I'm just wondering if it's a compiler website.

**Comment by OrangeThunderFire** [comment]
why do u need a securly disabler in teh first place do u play video games

**Comment by EEEEHI** [comment]
No- I don't play video games
I use it to go on discord and youtube mostly.
Oh and if you play games then you should use classroom 6x.

**Comment by EEEEHI** [comment]
Because you found something to make the hack work.

**Comment by OrangeThunderFire** [comment]
I know right!

**Comment by EEEEHI** [comment]
so ofc it works for u

**Comment by OrangeThunderFire** [comment]
thats a good thing no?

**Comment by EEEEHI** [comment]
Yeah- but the problem is it's not working for a lot of people. And it's not
like you're gonna share how you made it work.

**Comment by OrangeThunderFire** [comment]
exactly how do you get me so well

**Comment by EEEEHI** [comment]
Yeah this sucks.

**Comment by EEEEHI** [comment]
And it gets even worse because they started blocking classroom 6x too.

**Comment by OrangeThunderFire** [comment]
what sucks?

**Comment by OrangeThunderFire** [comment]
bro what are you even saying

**Comment by OrangeThunderFire** [comment]
can't u just be smart and get rid of it?

**Comment by EEEEHI** [comment]
Obv I tried

**Comment by OrangeThunderFire** [comment]
bro whats ur email, ill give you a interstellar

**Comment by EEEEHI** [comment]
***@***.***

**Comment by OrangeThunderFire** [comment]
bruh its in hashtags, give me ur school email

**Comment by EEEEHI** [comment]
My school email blocks other emails from other places

**Comment by EEEEHI** [comment]
artisticeli.xo

and gmail

**Comment by OrangeThunderFire** [comment]
imagine tho ill just post a link here cause why not

https://china.dingshun.hk/

**Comment by EEEEHI** [comment]
its blocked

**Comment by OrangeThunderFire** [comment]
shit, let me give another one https://bubbo.dev/

**Comment by EEEEHI** [comment]
that one too

**Comment by EEEEHI** [comment]
This one might actually work. But the connection was reset bc I'm at school. I'll test it out later.

**Comment by OrangeThunderFire** [comment]
Ok, let me know. remember you have to host your own bare server

**Comment by EEEEHI** [comment]
Okay. Thx

**Comment by mountedtheexo** [comment]
Im gonna be honest I tried Nebula and it wouldn't let me search on it

**Comment by mountedtheexo** [comment]
just realized i need to use a bare server

**Comment by OrangeThunderFire** [comment]
yeah ofc

**Comment by EEEEHI** [comment]
wait how do i host a bare server

**Comment by OrangeThunderFire** [comment]
._.

**Comment by EEEEHI** [comment]
lol

**Comment by mountedtheexo** [comment]
i  found something but im not spilling it

**Comment by EEEEHI** [comment]
cool

**Comment by EEEEHI** [comment]
what's the point in telling everyone you found something?

**Comment by mountedtheexo** [comment]
i have no idea honestly i was just happy. oh well I guess I'm kind of stupid for doing that

**Comment by EEEEHI** [comment]
lol jk its fine

**Comment by OrangeThunderFire** [comment]
how do you host a bare server anyway?

**Comment by EEEEHI** [comment]
yeah I heard that u have to buy stuff

**Comment by EEEEHI** [comment]
or like u need a whole system running
like its complicated

**Comment by EEEEHI** [comment]
idk how we're supposed to do it on a Chromebook tho

**Comment by EEEEHI** [comment]
Yeah.

**Comment by OrangeThunderFire** [comment]
can you buy a bare server and send it to me

**Comment by OrangeThunderFire** [comment]
Its around 5 dollars

**Comment by mountedtheexo** [comment]
whatever i was using got blocked lol

**Comment by EEEEHI** [comment]
buy one?

**Comment by EEEEHI** [comment]
oh that sucks  damn why does securly have to be so damn annoying

**Comment by OrangeThunderFire** [comment]
yeh

**Comment by mountedtheexo** [comment]
i don't even know how they blocked a bookmarklet and stopped it from
working

**Comment by mountedtheexo** [comment]
i was using zeks thing

**Comment by OrangeThunderFire** [comment]
same

**Comment by mountedtheexo** [comment]
what are we even doing lol

**Comment by OrangeThunderFire** [comment]
idk
