### ISSUE TITLE
Inadequate version of Securly(?)

### ISSUE THREAD

**Issue by rockguitarbandhero0192** [HXCHS/HackersX-Unblocked-Websites#23]
Looks like i have a inadequate version of securly? The version of securly i have is "1.24.1".

![image](https://github.com/HXCHS/HackersX-Unblocked-Websites/assets/84370024/3276dbdb-3950-4e3b-b298-4ac3e77a482b)

**Desktop (please complete the following information):**
 - OS: [ChromeOS]
 - Browser [Chrome]
 - Version [120.0.6099.272]

**Comment by EEEEHI** [comment]
how do u even check the securly version?

**Comment by rockguitarbandhero0192** [comment]
by going to manage extensions?
