### ISSUE TITLE
ubhub no longer working

### ISSUE THREAD

**Issue by Sparklingpeackock67612** [HXCHS/HackersX-Unblocked-Websites#28]
![Screenshot 2024-02-22 10 29 16 AM](https://github.com/HXCHS/HackersX-Unblocked-Websites/assets/151665987/6f82b8fa-e15a-4147-8849-e6517973d8a1)

**Comment by Sparklingpeackock67612** [comment]
not sure what's wrong, its just stopped working for me, can you add an alternative?

**Comment by DaOne2460** [comment]
yeah why it stop

**Comment by robotacwqr** [comment]
same

**Comment by HeroLink6** [comment]
Yea, it stopped, I think the owner needs to reboot it.

**Comment by HeroLink6** [comment]
@HXCHS not sure what happened, but it seems that everything else is blocked except for ubhub, and now that is gone too. Heroku might be doing something weird, or something else, but I (and probably a lot of other people) would be very happy if you could try to fix this, please. Thanks! 🙂

**Comment by HeroLink6** [comment]
Heroku is blocked for me 😢 And replit and glitch is also blocked, and I also can't do render right now. So, I am kinda screwed.

**Comment by Sparklingpeackock67612** [comment]
> @Sparklingpeackock67612 Can you do another Heroku deployment?? The link to the code for ubhub is [here](https://github.com/TheUnblockedHubOfficial/UBH-V1)

I don't really know how this works, I've just been using 69.eighthgrade, while it's super slow, it's the best option for now. Also, if you haven't tried redoing the securly remover, I would. It may not work for you, but it does for me, the only reason I need a proxy is because of network filters. As long as you're not on school wifi it should work. You can also try using a hotspot in that case.

**Comment by HeroLink6** [comment]
Fair, My friend Emailed the owner, and they said they are aware, and working on it.

**Comment by HeroLink6** [comment]
I don't have a hotspot, and my school uses ContentKeeper, not Securly. So, I rely on the links a lot more, and my school has a WiFi Blocker.
