### ISSUE TITLE
Securly isnt working for me

### ISSUE THREAD

**Issue by gh0la** [HXCHS/HackersX-Unblocked-Websites#8]
When i drag the button in a new tab then click the button to turn off securly it doesn't work. I go to a usually blocked website and it wouldn't show up that securly blocked it it shows "this site cant be reached"

**Comment by HXCHS** [comment]
Whats the site?

**Comment by gh0la** [comment]
> Whats the site?

it was any site but the one i did it on was roblox.com but i fixed the issue. I found out not only do they have securly blocking things if your connected to their wifi it will also block things. I used a hotspot and now its working.

**Comment by gh0la** [comment]
> What button do I drag?

the button with the words "drag this button into a new tab!" drag it into a new tab

**Comment by HXCHS** [comment]
@gh0la Yea, this wont help wifi blockers.

**Comment by OrangeThunderFire** [comment]
HCXHS, this is a masterpiece, while recoding it you should try to make it bypass iboss as well and wifi restrictions, you are a real good coder you should start a security company when you get older lol

**Comment by laparda14** [comment]
I found a website that can let you view a link if you sign up for free:
Mobilemoxie.com
